name = "blinky"
runtime_target = "stm32f100rb"

run_command = [ 
  "qemu-system-arm",
  "-machine", "stm32vldiscovery",
  "-cpu", "cortex-m3",
  "-nographic",
  "-semihosting-config", "enable=on,target=native",
  "-m", "16M",
  # uncomment the following lines to enable debugging
  # connect to gdb with `arm-none-eabi-gdb blinky.elf -ex "target remote localhost:1234"`
  #  "-S", "-s",
  # "-serial", "mon:stdio",
  "-kernel", "{elf_file}"
]

linker_args = [ "-Tlinker.ld" ]

[target]
triple = "thumbv7m-none-eabi"
cpu = "cortex-m3"

