name = "blinky"
run_command = [ 
"qemu-system-arm",
"-machine"
    ; "mps2-an505"
    ; "-cpu"
    ; "cortex-m33"
    ; "-nographic"
    ; "-semihosting-config"
    ; "enable=on,target=native"
    ; "-m"
    ; "16M"
    ; "-kernel"
    ; "{elf_file}" ]

[target]
cpu = "cortex-m33"

