name = "blinky"

run_command = [ 
  "qemu-system-arm",
  "-machine", "mps2-an505",
  "-cpu", "cortex-m33",
  "-nographic",
  "-semihosting-config", "enable=on,target=native",
  "-m", "16M",
  # uncomment the following lines to enable debugging
  # connect to gdb with `arm-none-eabi-gdb blinky.elf -ex "target remote localhost:1234"`
  #  "-S", "-s",
  # "-serial", "mon:stdio",
  "-kernel", "{elf_file}"
]

linker_args = [ "-Tlink.x" ]

[target]
triple = "thumbv8m.main-none-eabihf"
cpu = "cortex-m33"

