external rpi_pac : i32 -> i32 = "mucaml_rpi_pac"
external rpi_pins : i32 -> i32 = "mucaml_rpi_pins"
external rpi_timer : i32 -> i32 = "mucaml_rpi_timer"
external rpi_timer_sleep_500ms : i32 -> i32 = "mucaml_rpi_timer_sleep_500ms"
external rpi_pin : i32 -> i32 = "mucaml_rpi_pin"
external rpi_pin_set_high : i32 -> i32 = "mucaml_rpi_pin_set_high"
external rpi_pin_set_low : i32 -> i32 = "mucaml_rpi_pin_set_low"



let main x : i32 =
  let pac = rpi_pac 0 in
  let pins = rpi_pins pac in
  let timer = rpi_timer pac in
  let pin = rpi_pin pins in
  let _ = rpi_timer_sleep_500ms timer in
  let _ = rpi_pin_set_high pin in
  let _ = rpi_timer_sleep_500ms timer in
  let _ = rpi_pin_set_low pin in
  let _ = rpi_timer_sleep_500ms timer in
  let _ = rpi_pin_set_high pin in
  let _ = rpi_timer_sleep_500ms timer in
  let _ = rpi_pin_set_low pin in
  let _ = rpi_timer_sleep_500ms timer in
  let _ = rpi_pin_set_high pin in
  let _ = rpi_timer_sleep_500ms timer in
  let _ = rpi_pin_set_low pin in
  let _ = rpi_timer_sleep_500ms timer in
  let _ = rpi_pin_set_high pin in
  let _ = rpi_timer_sleep_500ms timer in
  let _ = rpi_pin_set_low pin in
  let _ = rpi_timer_sleep_500ms timer in
  let _ = rpi_pin_set_high pin in
  let _ = rpi_timer_sleep_500ms timer in
  let _ = rpi_pin_set_low pin in
  let _ = rpi_timer_sleep_500ms timer in
  let _ = rpi_pin_set_high pin in
  let _ = rpi_timer_sleep_500ms timer in
  let _ = rpi_pin_set_low pin in
  let _ = rpi_timer_sleep_500ms timer in
  let _ = rpi_pin_set_high pin in
  let _ = rpi_timer_sleep_500ms timer in
  let _ = rpi_pin_set_low pin in
  let _ = rpi_timer_sleep_500ms timer in
  let _ = rpi_pin_set_high pin in
  let _ = rpi_timer_sleep_500ms timer in
  let _ = rpi_pin_set_low pin in
  let _ = rpi_timer_sleep_500ms timer in
  let _ = rpi_pin_set_high pin in
  let _ = rpi_timer_sleep_500ms timer in
  let _ = rpi_pin_set_low pin in
  let _ = rpi_timer_sleep_500ms timer in
  let _ = rpi_pin_set_high pin in
  let _ = rpi_timer_sleep_500ms timer in
  let _ = rpi_pin_set_low pin in
  let _ = rpi_timer_sleep_500ms timer in
  let _ = rpi_pin_set_high pin in
  let _ = rpi_timer_sleep_500ms timer in
  let _ = rpi_pin_set_low pin in
  let _ = rpi_timer_sleep_500ms timer in
  let _ = rpi_pin_set_high pin in
  let _ = rpi_timer_sleep_500ms timer in
  let _ = rpi_pin_set_low pin in
  1000

